# Site settings
title: 실마리의 삽질들
email: nobody@nowhere.net
description: "프로그래밍과 관련된 개인적인 공부와 팁들의 기록을 남겨놓는 곳입니다."
baseurl: ""
url: "https://nineclue.github.io"
twitter_username: none
github_username:  nineclue

timezone: KO
encoding: utf-8

# Build settings
markdown: kramdown
permalink: pretty
